### PR TITLE
add full-throttle feature

### LINKED ISSUE #43: Integrate with the ergo ecosystem
Hey @killercup, you've probably been waiting for this feature request 😄 

I am nearing completion of the initial release of [`ergo`](https://github.com/rust-crates/ergo). There is a LOT of overlap between these two crates but there is also several areas that there is not overlap.

My suggestion is to have a `minimal` feature set which only 
- exports the `main!` macro
- exports `log` and `envlog` crates and types
- exports `structopt` macro and types
- exports `failure` macros and types

This would allow quicli to fit cleanly within the ergo crate ecosystem, as I have no desire for ergo to perform these operations. Theoretically I could create an `ergo-cli` crate which is pretty much a fork of quicli with these features -- but I don't want to do that!

Another advantage of this is that it could be part of the "story" of developing an application:
- when you start out, use just quicli
- when you need a larger stdlib, set `features=minimal` and import ergo
- keep rusting!

### PR DESCRIPTION
**Pull request by vitiral**
fix #43 

This is a second attempt at #51

### CODE REVIEW

**Comment by vitiral** [comment]
also, `rustfmt` went ahead and formatted things... I need to figure out how disable it for this repo.

**Comment by vitiral** [comment]
@killercup this should be ready. Any chance you can take a look?

**Comment by killercup** [comment]
I'm planning to do another quicli release soon and consolidate all the PRs and updates to libraries then in one go :)

**Comment by killercup** [comment]
Thanks again! Will release a new version with this feature soon

**Pull request merged**
