### PR TITLE
Allow mut args

### PR DESCRIPTION
**Pull request by CAD97**
(in the most annoying way)

This is useful for when you want to do more complicated manual defaults for arguments, such as trying to read from an environment variable if an argument is not provided.

### CODE REVIEW

**Comment by CAD97** [comment]
Here's the current (working) `main!` I have in the crate that caused me to submit this:

```rust
main!(|args: Args, log_level: verbosity| {
    let args = Args {
        token: args.token.or(option_env!("GH_TOKEN").map(ToOwned::to_owned)),
        ..args
    };
    ghp_upload(args)?;
});
```

**Comment by killercup** [comment]
I don't see why you need the mutable bit – just use `args.clone()`. It's totally irrelevant for performance unless your CLI arguments are _megabytes_ of data (and even then LLVM can probably optimize this).

**Comment by killercup** [comment]
Additionally, the proper solution for what your example shows is to have a better story around configuration management. See #21 for some ideas how to use config files, env vars, and cli args.

**Comment by CAD97** [comment]
Makes sense.

The error message rustc spits out when putting a mut there is .... confusing though; I think it gets grabbed by the `$expr` case.

**Comment by CAD97** [comment]
(Just realized that I meant to use `env::var("GH_TOKEN")` and not `option_env!("GH_TOKEN")` in the example, because I just fixed that in the example it came from)

**Pull request closed without merging**
