### PR TITLE
Use globwalk instead of glob

### PR DESCRIPTION
**Pull request by h-michael**
implementation of #74 .

Now, we can use `{a, b}` pattern.

### CODE REVIEW

**Comment by killercup** [comment]
Having a max depth is fine with me. Maybe you can document this, though?

Also, if you rebase on master, CI should be fixed.

**Comment by h-michael** [comment]
> Having a max depth is fine with me. 

Should we change glob function argument from `(patterns: &str) to `(patterns: &str, min_depth: Option<u32>, max_depth: Option<u32>)`

**Comment by killercup** [comment]
> Should we change glob function argument from (patterns: &str) to (patterns: &str, min_depth: Option, max_depth: Option)

Nah, quicli is about giving you simple functions. Let's just use the defaults for now and add comment saying "If you need to work with very deeply nested directories, please use the globwalk crate directly."

**Comment by killercup** [comment]
Ah, CI is green already. Thanks for contributing this!

**Comment by killercup** [comment]
I'm not sure I understand? I'd expect `*.md` to only check for files ending with `.md` in the current directory. `**/*.md` I expect to find markdown files in subdirectories up -- up to the limit you describe.

What are you proposing we do?

**Comment by h-michael** [comment]
@killercup 

I am sorry that I was not good at English, so if I did not convey it to you.
I mean that this PR contains a Breaking change.
I will explain it using existing tests.

This test is not changed my PR.
https://github.com/killercup/quicli/blob/master/src/fs.rs#L91

But if we added test case like this, using `glob` could pass this but using `globwalk` that is my commit couldn't pass this case because of limitting max_depth.
```
/// let markdown_files = glob("**/*.md")?;
/// assert_eq!(markdown_files.len(), 5);
```


So if I tried to remove max_depth method, it could pass above case.
But it could not this case.
This case gets 5.

```
/// let markdown_files = glob(*.md")?;
/// assert_eq!(markdown_files.len(), 2);
```

Did you recognize this breaking change?
If you don't recognize this, how do you think about this?

Sorry for my poor English.

**Pull request merged**
