### PR TITLE
Allow verbosity to not be called verbosity

### PR DESCRIPTION
**Pull request by CAD97**
(How do I add a test for this)

### CODE REVIEW

**Comment by killercup** [comment]
(Restarted the build, CI should pass now.)

Re tests: I've been meaning to add a good testing story, aside from the doc tests. For now, I'd just add something like `examples/verbosity_by_any_other_name_is_still_as_verbose.rs` :)

**Comment by CAD97** [comment]
Added an example with the first absurd field name to come to mind.

**Comment by CAD97** [comment]
Added example can now be used to show off `-vvv`'s behavior, and.... it doesn't seem to be doing anything.

**Comment by killercup** [comment]
Let's land this right now as its a valuable fix. (I'll also add a change log entry.)

bors r+

**Pull request merged**
