### PR TITLE
Replace examples with guides!

### PR DESCRIPTION
**Pull request by killercup**
Also adds testing on CI. Rending this in some way other than on github.com will come at a later point.

#### Required to land this

- [x] Set up waltz on Travis
- [x] Move over Readme guide
- [x] Move over commit guide

#### Stretch goals

- [ ] Cache target dir between crates generated waltz
- [x] Set up github pages rendering with simple template
- [ ] Move over image resize guide from #23

cc #16

### CODE REVIEW

**Comment by killercup** [comment]
What do you think, @vitiral?

I'm not sure about moving the getting started guide out of the readme, but otherwise I think this is quite a good format that mixes guide and recipe style.

**Comment by vitiral** [comment]
This is really cool! I'm working on getting `ergo_fs` pushed now, will definitely eventually incorporate this kind of "book style" into `ergo`.

**Comment by killercup** [comment]
Glad you like it @vitiral!

I'll try to have some time to get a simple github pages setup going. Ideally, it'll use a custom (but external) theme, so it should be only a matter of adding two or three files to get a nice rendered version of website with these guides.

**Comment by killercup** [comment]
Alright, Jekyll with custom theme set up! I still need to configure this once it is in master to render, though.

You can find the theme I wrote in <https://github.com/killercup/jekyll-theme-rustguides>. I haven't spend much time writing CSS for this, but I did make it possible to customize the main color. For quicli, I chose dark blue (at random, basically). The layout is quite barebones right now. It has a list of pages (currently just the one for the commit.md guide), but there is not footer or anything like that.

bildschirmfoto 2018-01-27 um 19 17 31

I think I'll land this tonight, because I won't have much time to work on this for the next week. Feedback (now or later) is very welcome! :)

**Pull request merged**
