### PR TITLE
Make head example main more concise

### PR DESCRIPTION
**Pull request by killercup**
Is this (more) readable? Can people new to Rust easily understand this code? Do they feel like they can write this themselves?

```rust
main!(|args: Cli, log_level: verbosity| {
    read_file(&args.file)?
        .lines()
        .take(args.count)
        .for_each(|line| println!("{}", line));
});
```

### CODE REVIEW

**Comment by itkovian** [comment]
The splitting across lines is nicer :)

**Comment by killercup** [comment]
I'll probably add some explanation how the iterator chain works (was asked [on twitter](https://twitter.com/mllnmchld/status/958648059323408385) – thanks!)

**Comment by Andy-Bell** [comment]
New(ish) to rust, this makes sense what it is doing

**Comment by killercup** [comment]
Thanks everyone who replied here and [on Twitter](https://twitter.com/killercup/status/958647275831660544)! Will merge this for now but am always looking for more feedback!

**Comment by igbanam** [comment]
This reads clear enough. 

p.s: This is the first Rust-y code snippet I'm looking at.

**Pull request merged**
